### ISSUE TITLE
Crash when using Mohist as server loader

### ISSUE THREAD

**Issue by andrebpessoa** [Gabriel-Hiss/Im-Fast#1]
When I put the mod on the server, it crashes when loading the mixins. I removed all the mods and tested them one by one to see if the problem was with i'm fast...

Information:
- Minecraft 1.20.1
- Forge 47.3.11
- Mohist 1.20.1-898
- Java(65.0) 21.0.5

Logs [here](https://mclo.gs/PEjjm4M)

**Comment by Gabriel-Hiss** [comment]
I'm working on it now to find a fix. It's like it isn't finding the class to modify.

**Comment by Gabriel-Hiss** [comment]
sorry for the late response

**Comment by Gabriel-Hiss** [comment]
Done i will release a new 1.20.1 version

**Comment by Gabriel-Hiss** [comment]
I have uploaded the file to CurseForge. The filename is 'imfast-FORGE-1.20.1-1.0.1'. I hope you enjoy it. I'm Fast!

**Comment by Gabriel-Hiss** [comment]
Done
