### ISSUE TITLE
add boat moved wrongly

### ISSUE THREAD

**Issue by VaporeonScripts** [Gabriel-Hiss/Im-Fast#2]
[19:14:07] [Server thread/WARN] [minecraft/ServerGamePacketListenerImpl]: Oak Boat (vehicle of NatsuyamiOnArch) moved wrongly! 0.254504207521677

**Comment by Gabriel-Hiss** [comment]
how do you get this warning?

**Comment by VaporeonScripts** [comment]
by using a boat

**Comment by Darwin-Gabriel** [comment]
ok when i get home i will try what version and loader are you using

**Comment by VaporeonScripts** [comment]
latest, neoforge 1.21.1 .80, neotech reborn modpack

**Comment by Darwin-Gabriel** [comment]
ok when i get home i will try to fix
