### ISSUE TITLE
Forge Mods.toml mod ID issue

### ISSUE THREAD

**Issue by xIGBClutchIx** [Gabriel-Hiss/Im-Fast#3]
> [27Dec2024 18:44:29.284] [main/ERROR] [net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer/SCAN]: Locator {mods folder locator at /home/container/mods} found an invalid mod file net.minecraftforge.fml.loading.moddiscovery.ModFileInfo@5c41d037
> net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Invalid modId found : imfast-FORGE-1.21.4 (imfast-FORGE-1.21.4-1.0.2.jar)

Looks like the mods.toml modid has the version in the ID `imfast-FORGE-1.21.4`, and it shouldn't. It should just be `imfast`.

**Comment by Gabriel-Hiss** [comment]
done
